import bcrypt from 'bcryptjs';

const data = {

    users:[
        {
            name: 'John',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name: 'Jane',
            email: 'user@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        }
    ],

    products:[
        {
            name: 'T Shirt',
            slug: 't-shirt',
            category: 'Shirts',
            image: '/images/tshirt1.jpg',
            price: 200.00,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 5,
            description: 'A popular shirt',
        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image: '/images/slimshirt1.jpg',
            price: 90.00,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 3,
            countInStock: 20,
            description: 'A popular shirt',
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 90.00,
            brand: 'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'Smart looking pants',
        },
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 95.00,
            brand: 'Zara',
            rating: 2.9,
            numReviews: 13,
            countInStock: 10,
            description: 'A popular pants',
        },
        {
            name: 'Ladies Top',
            slug: 'ladies-top',
            category: 'Top',
            image: '/images/ladiestop.jpg',
            price: 95.00,
            brand: 'Zara',
            rating: 2.9,
            numReviews: 13,
            countInStock: 10,
            description: 'A popular Top',
        },
        {
            name: 'Ladies Stylish Top',
            slug: 'ladies-stylish-top',
            category: 'Stylish Top',
            image: '/images/stylish.jpg',
            price: 95.00,
            brand: 'Nara',
            rating: 2.9,
            numReviews: 13,
            countInStock: 10,
            description: 'A popular Stylish Top',
        },
        {
            name: 'Ladies Kurti Top',
            slug: 'ladies-kurti-top',
            category: 'Kurti Top',
            image: '/images/kurthi.jpg',
            price: 95.00,
            brand: 'Nara',
            rating: 2.9,
            numReviews: 13,
            countInStock: 10,
            description: 'A popular Kurti Top',
        },
        {
            name: 'Ladies Casual Shirt',
            slug: 'ladies-casual-top',
            category: 'Shirt',
            image: '/images/shirt.jpg',
            price: 95.00,
            brand: 'Nara',
            rating: 2.9,
            numReviews: 13,
            countInStock: 10,
            description: 'Casual Shirt for working women',
        },
        {
            name: 'Gold Necklace Full Set',
            slug: 'gold-necklace',
            category: 'Jewels',
            image: '/images/jewels1.jpg',
            price: 95.00,
            brand: 'Turkeys',
            rating: 2.9,
            numReviews: 13,
            countInStock: 10,
            description: 'Turkeys style jewels',
        },
        {
            name: 'Diamond Necklace',
            slug: 'diamond-necklace',
            category: 'Jewels',
            image: '/images/diamondnecklace.jpg',
            price: 500.00,
            brand: 'Royal',
            rating: 2.9,
            numReviews: 13,
            countInStock: 10,
            description: 'Beautiful royal diamond necklace',
        },
        {
            name: 'Ladies Handbag',
            slug: 'ladies-handbag',
            category: 'HandBag',
            image: '/images/handbag1.jpg',
            price: 230.00,
            brand: 'Louis',
            rating: 2.9,
            numReviews: 13,
            countInStock: 10,
            description: 'Stylish Handbags from louis',
        }
    ]
}


export default data
